# This is a workflow for continuous integration using GitHub Actions
name: Rust CI

# Specifies when the workflow should run
on:
  push:
    branches: [ main, dev ]  # Triggers the workflow on push events to main and dev branches
  pull_request:
    branches: [ main, dev ] # Also triggers the workflow on pull requests to these branches

# Defines the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment, using the latest Ubuntu version

    steps:
    - uses: actions/checkout@v2
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable  # Sets the Rust toolchain to the stable version
        profile: minimal   # Minimal installation - installs only essential components
        override: true     # Forces the use of the specified toolchain

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build  # Compiles the code using Cargo

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test   # Runs tests using Cargo
  
